// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlerq6ac7JAgvMbA3XLbYNCAWLur2eRBw',
    appId: '1:760451399412:web:7394eca53b70a3f6e6e8a1',
    messagingSenderId: '760451399412',
    projectId: 'live-score-5eaec',
    authDomain: 'live-score-5eaec.firebaseapp.com',
    storageBucket: 'live-score-5eaec.firebasestorage.app',
    measurementId: 'G-26FQBPTBVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgv4y9ecPsRqpBqbBc7cAAIF00ZXuWR1k',
    appId: '1:760451399412:android:11a8d00da5cbab4ee6e8a1',
    messagingSenderId: '760451399412',
    projectId: 'live-score-5eaec',
    storageBucket: 'live-score-5eaec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhEta0CL74XG8Q0Em9XA1QOFab6jBGyXs',
    appId: '1:760451399412:ios:10f39afd5a894345e6e8a1',
    messagingSenderId: '760451399412',
    projectId: 'live-score-5eaec',
    storageBucket: 'live-score-5eaec.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLiveScoreProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhEta0CL74XG8Q0Em9XA1QOFab6jBGyXs',
    appId: '1:760451399412:ios:10f39afd5a894345e6e8a1',
    messagingSenderId: '760451399412',
    projectId: 'live-score-5eaec',
    storageBucket: 'live-score-5eaec.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLiveScoreProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlerq6ac7JAgvMbA3XLbYNCAWLur2eRBw',
    appId: '1:760451399412:web:6b3f58b666508dcee6e8a1',
    messagingSenderId: '760451399412',
    projectId: 'live-score-5eaec',
    authDomain: 'live-score-5eaec.firebaseapp.com',
    storageBucket: 'live-score-5eaec.firebasestorage.app',
    measurementId: 'G-K0Z00GSB16',
  );
}
